# Configuration for SIREN Flash Matching Inference with HDF5 Data
# This config uses the new FlashMatch HDF5 dataset format

torchscript: 
  device: cpu
  #output_path: siren_model_corsika_desert_universe_ckpt685k.pt
  #output_path: siren_model_corsika_lemon_snowflake_ckpt382k.pt
  output_path: siren_model_corsika_lemon_snowflake_ckpt634k.pt
  example_num_voxels: 500
  example_batch_size: 1
  
# Data Loader Configuration
dataloader:
  # File lists (can be paths to .txt files or directories)
  #valid_filelist: "inference_validation_test_dataset.txt"
  valid_filelist: "filelist_mcc9_v13_mccorsika_inference.list"
  debug: True
  
  # Batch configuration
  batchsize: 16                # Batch size for training
  shuffle: false               # Shuffle training data
  num_workers: 4              # Number of data loading workers
  pin_memory: false           # Pin memory for faster GPU transfer
  persistent_workers: false   # Keep workers alive between epochs
  
  # Data augmentation
  use_mixup: false            # Use the Mix-Up data reader
  mixup_prob: 0.5             # Probability of applying MixUp (0 = disabled)
  mixup_alpha: 1.0            # Beta distribution parameter for MixUp
  augment_scale: false        # Apply random scaling augmentation
  augment_jitter: false       # Apply position jittering
  
  # Data preprocessing
  max_voxels: 500             # Maximum voxels per sample
  normalize_features: true    # Apply feature normalization
  
  # Normalization parameters (from calculate_means_vars.py)
  # only log is being used right now
  pmt_norm_params:
    transform: "linear"          # Transform type: "log", "sqrt", "none"
    offset: 0.0               # Offset after log(1 + x)
    scale: 1000.0                # Scale factor
    
  planecharge_norm_params:
    transform: "linear"          # Transform type per plane
    offset: [0.0, 0.0,0.0]   # Offsets for U, V, Y planes
    scale: [50000.0, 50000.0, 50000.0]    # Scale factors for U, V, Y planes
    
  position_norm_params:
    scale: 100.0              # Divide positions by this value
    center: true              # Center positions around detector center

# Model Configuration
model:

  # Model weights
  #checkpoint: ./checkpoints/snowy_dust_checkpoint_iteration_00782000.pt # Path to checkpoint file if resuming"
  #checkpoint: ./checkpoints/desert_universe_checkpoint_iteration_00685000.pt # trained on run 3 extbnb cosmic reco data
  #checkpoint: ./checkpoints/lemon_snowflake_checkpoint_iteration_00382000.pt # trained on mcc9 v13 corsika simulated data
  checkpoint: ./checkpoints/lemon_snowflake_checkpoint_iteration_00634000.pt # trained on mcc9 v13 corsika simulated data
  
  # Input embedding options
  use_cos_input_embedding_vectors: false  # Use cosine embeddings
  embedding_dim: 64                       # Dimension of embeddings

  
  # FlashMatchMLP configuration (for baseline/embeddings)
  flashmlp:
    input_nfeatures: 112                  # Input feature dimension
    hidden_layer_nfeatures: [512, 512, 512, 512, 512]  # Hidden layer sizes
    dropout: 0.1                          # Dropout probability
    activation: "relu"                    # Activation function
    batch_norm: false                     # Use batch normalization
    
  # SIREN Light Model configuration
  lightmodelsiren:
    # Architecture
    dim_in: 7                             # Input: (x,y,z,dx,dy,dz,dist)
    dim_hidden: 512                       # Hidden layer dimension
    dim_out: 1                            # Output: light intensity
    num_layers: 5                         # Number of SIREN layers
    use_logpe: false                      # if True, output log(PE), else PE
    
    # SIREN-specific parameters
    w0_initial: 30.0                      # Initial frequency (hyperparameter)
    w0_hidden: 1.0                        # Hidden layer frequency
    final_activation: "identity"          # Final layer activation
    use_bias: true                        # Use bias terms
    
    # Advanced options
    weight_norm: false                    # Apply weight normalization
    spectral_norm: false                  # Apply spectral normalization

